---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: get code
  commands:
  - git pull origin master
  volumes:
  - name: tmp
    path: /tmp/blog

- name: install
  image: node
  commands:
  - yarn --version
  - yarn install --force

- name: build
  image: node
  commands:
  - yarn build

volumes:
- name: tmp
  host:
    path: /root/blog

...
