---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node
  commands:
  - yarn --version
  - yarn install --force
  volumes:
  - name: tmp
    path: /root/blog/dist

- name: build
  image: node
  commands:
  - yarn build

volumes:
- name: tmp
  host:
    path: /root/blog/dist

...
