kind: pipeline
name: default

steps:
- name: get code
  volumes:
  - name: tmp
    path: /tmp/blog
  commands:
  - git pull origin master

- name: install
  image: node
  commands:
  - yarn --version
  - yarn install --force

- name: build
  image: node
  commands:
  - yarn build

volumes:
- name: tmp
  host:
    path: /root/blog
