---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node
  commands:
  - npm install

- name: build
  image: node
  commands:
  - npm run build
  volumes:
  - name: tmp
    path: /root/blog/dist

volumes:
- name: tmp
  host:
    path: /root/blog/dist

...
