---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node
  commands:
  - yarn --version
  - yarn config set registry https://registry.npm.taobao.org
  - yarn install

- name: build
  image: node
  commands:
  - yarn build
  volumes:
  - name: tmp
    path: /root/blog/dist

volumes:
- name: tmp
  host:
    path: /root/blog/dist

...
